### PR TITLE
Add spacing behind email

### PR DESCRIPTION
**Pull request by karelhala**
Screenshot from 2020-04-20 18-37-15
Screenshot from 2020-04-20 19-16-33

### CODE REVIEW

**Comment by karelhala** [comment]
ping @mmenestr

**Comment by mmenestr** [comment]
Desktop spacing looks good!
For mobile, is it possible to reduce the spacing between the email and link? What is the spacing right now?

**Comment by karelhala** [comment]
@mmenestr updated the spacing to be 8px.

**Comment by mmenestr** [comment]
looks good! thanks Karel!

**Pull request merged**
