### PR TITLE
Sync to prod-beta

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@josejulio there is a bug on prod beta which requires this sync. Is there anything else before we can mark this PR ready to be merged?

**Comment by josejulio** [comment]
Not on my computer right now, all but the last commit are fine to be merged in both beta and stable.

**Comment by Hyperkid123** [comment]
@josejulio you think it will be ready by Monday? If not it's fine Ill create new PR without the: https://github.com/RedHatInsights/user-preferences-frontend/pull/68/commits/290eb2f121495491b40c11d06e155c6dae9e45d9 commit.

**Comment by josejulio** [comment]
We are preparing to merge to beta/stable at about 4pm CEST (Monday)

**Comment by josejulio** [comment]
Also ready to merge

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
