### PR TITLE
NOTIF-757 (prod-beta) Adding "console" and updating order

### PR DESCRIPTION
**Pull request by josejulio**

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Comment by josejulio** [comment]
Looks like this wasn't deployed in prod-beta - I was trying there and the json within the [js](https://console.redhat.com/beta/apps/user-preferences/js/812.c0b99b06cb97bf55f8a8.js) is:
```
{
   "email-preference":{
      "advisor":{
         "title":"Advisor",
         "url":"/user-preferences/",
         "apiName":"insights",
         "permissions":[
            {
               "method":"hasLoosePermissions",
               "args":[
                  [
                     "insights:*:*",
                     "insights:*:read",
                     "advisor:*:*",
                     "advisor:*:read",
                     "advisor:rules:read"
                  ]
               ]
            }
         ]
      },
      "unsubscribe":{
         "title":"",
         "localFile":"data/unsubscribe.json"
      }
   },
   "notification-preference":{
      "rhel":{
         "title":"Red Hat Enterprise Linux",
         "application":"notifications",
         "resourceType":"notification-preference?bundleName=rhel"
      },
      "openshift":{
         "title":"OpenShift",
         "application":"notifications",
         "resourceType":"notification-preference?bundleName=openshift"
      },
      "application-services":{
         "title":"Application Services",
         "application":"notifications",
         "resourceType":"notification-preference?bundleName=application-services"
      }
   }
}
```

Wondering if we are missing something to deploy this to prod-beta.

**Comment by Hyperkid123** [comment]
Yeah, the build repo does have the new commit. Let me see what is going on.

**Comment by Hyperkid123** [comment]
It looks like the travis key is either expired or somehow currputed.

**Comment by josejulio** [comment]
Is there any process to restore the travis key or is the work needed being tracked somewhere?
Thanks!

**Comment by Hyperkid123** [comment]
Yeah I have created a ticket in our board. Send me a PM if you want to take care of it. I am unfortunately busy with other things ATM.

**Pull request merged**
