### PR TITLE
Align items on mobile view

### PR DESCRIPTION
**Pull request by karelhala**
# Mobile view
Screenshot from 2020-03-18 17-59-06

# Large screen view
Screenshot from 2020-03-18 16-18-51

### CODE REVIEW

**Comment by karelhala** [comment]
@mmenestr what do you think?

**Comment by mmenestr** [comment]
Yes, looks great! Only thing is I would put the same spacing above and below the "unsubscribe from all button" because right now there's way more space below. I would say make it the same spacing above as it is below currently!

**Comment by ryelo** [comment]
@karelhala what's the email field look like with a superduperlongemail@emailemailemail.com?

**Comment by karelhala** [comment]
@ryelo good point! Updated css to word-break long lines.

@mmenestr aligned the spacing to be same above and bolow on mobile view, is that correct? Or do you want to align spacing on large screen as well?

**Comment by mmenestr** [comment]
I meant make the spacing at the top bigger, not make the bottom smaller ahha can you make the spacing above an below 24px? or 32px if that's too close. Can't remember what we had concluded on our call?

And the spacing on desktop looks fine to me!

**Comment by karelhala** [comment]
@mmenestr oh shoot! Updated. Added 24px, it looks even with other parts of UI.

**Comment by mmenestr** [comment]
Perfect, thank you!

**Pull request merged**
