### PR TITLE
Align email information to values

### PR DESCRIPTION
**Pull request by karelhala**
Screenshot from 2020-04-14 17-40-05

Screenshot from 2020-04-14 17-44-37

### CODE REVIEW

**Comment by karelhala** [comment]
ping @mmenestr

**Comment by mmenestr** [comment]
Hey, can you include a screen shot that has the insights email preferences in it?

**Comment by karelhala** [comment]
@mmenestr sure thing, just bear in mind that insights is using incorrect schema, meaning incorrect component so their spacing is off. There's already a PR opened to address that https://github.com/RedHatInsights/insights-advisor-api/pull/516
Screenshot from 2020-04-14 17-03-04

**Comment by karelhala** [comment]
@mmenestr I've removed extra spacing in checkboxes in order to align everything properly.

**Comment by mmenestr** [comment]
Ok thanks! So per your message on slack ---> "About the user preferences spacing, if we' want to avoid future misalignments what do you think about this approach (removing extra space between checkbox and title)"  I think we should go ahead and do that, and i'm fine with removing the extra spacing! I only care that everything is aligned :)

**Pull request merged**
